name: tests

# CINTENT >> MANUAL_TRIGGER
# on:
#   pull_request:
#     branches:
#       - master
on: [repository_dispatch, workflow_dispatch]

jobs:
  run-tests:
    # CINTENT >> CHANGE_VERSION
    # runs-on: ubuntu-22.04 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                  freeglut3-dev \
                  libcurl4-openssl-dev \
                  libexpat1-dev \
                  libgl1-mesa-dev \
                  libglu1-mesa-dev \
                  libgtk-3-dev \
                  libjpeg-dev \
                  libnotify-dev \
                  libsdl2-dev \
                  libsm-dev \
                  libtiff-dev \
                  libwebkit2gtk-4.0-dev \
                  libxtst-dev \
                  libunwind-dev \
                  libgstreamer1.0-dev \
                  libgstreamer-plugins-base1.0-dev \
                  libpng-dev \
                  libxrandr-dev \
                  libxinerama-dev \
                  libxcursor-dev \
                  libxcomposite-dev \
                  libfreetype6-dev \
                  libxi-dev \


      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          # CINTENT >> REMOVE_CACHE
          # enable-cache: true
          # cache-dependency-glob: "uv.lock"

      - name: Syncing with UV
        run: uv sync

      - name: Run tests with xvfb
        run: xvfb-run -a bash -c "pytest"

      # CINTENT >> REMOVE_CACHE
      # - name: Minimize uv cache
      #   run: uv cache prune --ci

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  # CINTENT >> NO_CI
  # combined-checks:
  #   runs-on: ubuntu-22.04
  #   needs: [run-tests]
  #   steps:
  #     - run: echo "All checks passed! Ready to merge."
